name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  upload-all:
    if: ${{ vars.SITE_TYPE == '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload directory
        id: upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./

  upload-v1:
    if: ${{ vars.SITE_TYPE == 'v1' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload directory
        id: upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./


  upload-v2:
    if: ${{ vars.SITE_TYPE == 'v2' }}  # workflow disabled; remove or change to enable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload  directory
        id: upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: v2/

  build-and-upload-v3:  
    if: ${{ vars.SITE_TYPE == 'v3' }}  # workflow disabled; remove or change to enable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install jinja2

      - name: Build site
        run: python ./build-v3.py

      - name: Upload build directory
        id: upload
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/

  # Deployment job
  deploy:
    needs: [upload-all, upload-v1, upload-v2, build-and-upload-v3]
    environment:
      name: github-pages
      url: ${{ steps.upload.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4